sudo: required
services:
  - docker

before_install:
  - docker build -t kapalal/docker-react -f Dockerfile.dev .


script:
  - docker run kapalal/docker-react npm run test -- --coverage


deploy:
  - provider: elasticbeanstalk
    region:  "eu-west-3"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-624758150896"
    bucket_path: "docker-react"
    on:
       branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"  
